version: '3'

env:
  IMAGE_NAME: dino
  CONTAINER_NAME: dino

tasks:
  build:
    desc: build docker image
    cmd: docker build -t $IMAGE_NAME --force-rm=true --no-cache -f docker/Dockerfile ./docker

  up:
    desc: run docker container
    cmd: docker run --gpus all --rm --name $CONTAINER_NAME --shm-size=8g --env USER_ID=$(id -u) --env GROUP_ID=$(id -g) -v ${PWD}:/workspace -w /workspace -dit $IMAGE_NAME

  down:
    desc: stop docker container
    cmd: docker stop $CONTAINER_NAME

  exec:
    desc: exec docker container
    cmd: docker exec -it $CONTAINER_NAME bash

  pip:
    desc: pip install in docker container
    cmd: docker exec -it $CONTAINER_NAME pip install {{.CLI_ARGS}}

  test:
    desc: run test
    cmd: docker exec -it $CONTAINER_NAME python3 -m pytest -svv {{.CLI_ARGS}}

  train_resnet18:
    desc: run train
    cmds: 
    - | 
      docker exec -it $CONTAINER_NAME python3 -m torch.distributed.launch \
      main_dino.py \
      --arch resnet18 \
      --epochs 100 \
      --warmup_epochs 1 \
      --optimizer sgd \
      --lr 0.03 \
      --weight_decay 1e-4 \
      --weight_decay_end 1e-4 \
      --output_dir /workspace/outputs/resnet18


  train_vitt:
    desc: run train
    cmds: 
    - | 
      docker exec -it $CONTAINER_NAME python3 -m torch.distributed.launch \
      main_dino.py \
      --arch vit_tiny \
      --epochs 1000 \
      --warmup_epochs 10 \
      --output_dir /workspace/outputs/vit_tiny

  vis_vitt:
    desc: run vis
    cmds: 
    - |
      docker exec -it $CONTAINER_NAME python3 visualize_clusters.py \
      --arch vit_tiny \
      --weight_path /workspace/outputs/vit_tiny/checkpoint.pth \
      --output_dir /workspace/outputs/vit_tiny

  vis_resnet18:
    desc: run vis
    cmds: 
    - |
      docker exec -it $CONTAINER_NAME python3 visualize_clusters.py \
      --arch resnet18 \
      --weight_path /workspace/outputs/resnet18/checkpoint.pth \
      --output_dir /workspace/outputs/resnet18